In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/python_faq_dataset.csv')
print(df.head())

                                            question  \
0  !cat datasets/Admission_Predict.csv\r\nERROR:\...
1  "All O(1) functions take exactly the same amou...
2  "Could not find the version that satisfies the...
3  "Error: Tesseract (legacy) engine requested, b...
4  "No Python interpreter is selected. You need t...

                                              answer           source  \
0           Try !more datasets/Admission_Predict.csv  filtered_basics
1  False. O(1) means constant time. This means th...  filtered_basics
2  Please correct your spelling of pip install vi...  filtered_basics
3  Message is clear: you asked tesseract to use l...  filtered_basics
4  Use ctrl+shift+P and then search for "Python: ...  filtered_basics

      score               tags         topic  q_length  a_length  \
0  0.000000      python,pandas  data_science       134        40
1  1.200000             python  control_flow       118      1234
2 -0.099668  python,virtualenv       modules       513       111
3  0.197375   python,tesseract  control_flow       373       176
4  0.000000             python  control_flow       141        66

   quality_score    difficulty
0              2      advanced
1              6      beginner
2              3  intermediate
3              4      beginner
4              3      beginner

In [3]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (21677, 10)

Columns:
['question', 'answer', 'source', 'score', 'tags', 'topic', 'q_length', 'a_length', 'quality_score', 'difficulty']

In [4]:
print("=== BEFORE CLEANING ===")
print("Total rows:", len(df))
print("\nMissing values:")
print(df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

=== BEFORE CLEANING ===
Total rows: 21677

Missing values:
question            0
answer              0
source              0
score            1000
tags             1000
topic               0
q_length            0
a_length            0
quality_score       0
difficulty          0
dtype: int64

Duplicate rows: 0

In [5]:
# Fill missing values
df['score'] = df['score'].fillna(0)
df['tags'] = df['tags'].fillna('unknown')

print("=== AFTER CLEANING ===")
print(df.isnull().sum())

=== AFTER CLEANING ===
question         0
answer           0
source           0
score            0
tags             0
topic            0
q_length         0
a_length         0
quality_score    0
difficulty       0
dtype: int64

In [6]:
df.to_csv('../data/cleaned_python_faq.csv', index=False)
print("Saved successfully!")

Saved successfully!

In [1]:
from pypdf import PdfReader

In [2]:
reader = PdfReader("../data/thinkpython2.pdf")
print("Pages:", len(reader.pages))

Pages: 244

In [3]:
text = ""

for page in reader.pages:
    page_text = page.extract_text()
    if page_text:
        text += page_text + "\n"

print("Extraction complete")

Extraction complete

In [4]:
print(text[:3000])

Think Python
How to Think Like a Computer Scientist
2nd Edition, Version 2.4.0
Think Python
How to Think Like a Computer Scientist
2nd Edition, Version 2.4.0
Allen Downey
Green Tea Press
Needham, Massachusetts
Copyright © 2015 Allen Downey.
Green Tea Press
9 Washburn Ave
Needham MA 02492
Permission is granted to copy, distribute, and/or modify this document under the terms of the
Creative Commons Attribution-NonCommercial 3.0 Unported License, which is available at http:
//creativecommons.org/licenses/by-nc/3.0/.
The original form of this book is LATEX source code. Compiling this LATEX source has the effect of gen-
erating a device-independent representation of a textbook, which can be converted to other formats
and printed.
The LATEX source for this book is available from http://www.thinkpython.com
Preface
The strange history of this book
In January 1999 I was preparing to teach an introductory programming class in Java. I had
taught it three times and I was getting frustrated. The failure rate in the class was too high
and, even for students who succeeded, the overall level of achievement was too low.
One of the problems I saw was the books. They were too big, with too much unnecessary
detail about Java, and not enough high-level guidance about how to program. And they all
suffered from the trap door effect: they would start out easy, proceed gradually, and then
somewhere around Chapter 5 the bottom would fall out. The students would get too much
new material, too fast, and I would spend the rest of the semester picking up the pieces.
Two weeks before the ﬁrst day of classes, I decided to write my own book. My goals were:
• Keep it short. It is better for students to read 10 pages than not read 50 pages.
• Be careful with vocabulary. I tried to minimize jargon and deﬁne each term at ﬁrst
use.
• Build gradually. To avoid trap doors, I took the most difﬁcult topics and split them
into a series of small steps.
• Focus on programming, not the programming language. I included the minimum
useful subset of Java and left out the rest.
I needed a title, so on a whim I chose How to Think Like a Computer Scientist.
My ﬁrst version was rough, but it worked. Students did the reading, and they understood
enough that I could spend class time on the hard topics, the interesting topics and (most
important) letting the students practice.
I released the book under the GNU Free Documentation License, which allows users to
copy, modify, and distribute the book.
What happened next is the cool part. Jeff Elkner, a high school teacher in Virginia, adopted
my book and translated it into Python. He sent me a copy of his translation, and I had the
unusual experience of learning Python by reading my own book. As Green Tea Press, I
published the ﬁrst Python version in 2001.
In 2003 I started teaching at Olin College and I got to teach Python for the ﬁrst time. The
contrast with Java was striking. Students struggled less, learned more, worked on more
interesting projects, a

In [5]:
cleaned_text = text.replace("\n", " ")
cleaned_text = " ".join(cleaned_text.split())

print(cleaned_text[:1000])

Think Python How to Think Like a Computer Scientist 2nd Edition, Version 2.4.0 Think Python How to Think Like a Computer Scientist 2nd Edition, Version 2.4.0 Allen Downey Green Tea Press Needham, Massachusetts Copyright © 2015 Allen Downey. Green Tea Press 9 Washburn Ave Needham MA 02492 Permission is granted to copy, distribute, and/or modify this document under the terms of the Creative Commons Attribution-NonCommercial 3.0 Unported License, which is available at http: //creativecommons.org/licenses/by-nc/3.0/. The original form of this book is LATEX source code. Compiling this LATEX source has the effect of gen- erating a device-independent representation of a textbook, which can be converted to other formats and printed. The LATEX source for this book is available from http://www.thinkpython.com Preface The strange history of this book In January 1999 I was preparing to teach an introductory programming class in Java. I had taught it three times and I was getting frustrated. The fa

In [6]:
with open("../data/cleaned_thinkpython2.txt", "w", encoding="utf-8") as f:
    f.write(cleaned_text)

print("Saved successfully!")

Saved successfully!

In [7]:
import pandas as pd
import json

In [9]:
essay_df = pd.read_csv('../data/essay_assistance_raw.csv')
essay_df.head()

,id,essay_topic,subject,grade_level,agent_type,word_count,grammar_score,structure_score,originality_score,overall_score,feedback_given,timestamp
0,ES001,Impact of social media on youth,English,11,Essay Writing,520.0,88,90,85,87,Yes,2024-01-10 13:00:00
1,ES002,Climate change and its effects,Environmental Science,12,Essay Writing,610.0,92,88,90,90,Yes,2024-01-11 14:00:00
2,ES003,Role of technology in education,English,10,Essay Writing,NaN,75,70,80,75,No,2024-01-11 15:00:00
3,ES004,Importance of biodiversity,Biology,11,Essay Writing,480.0,85,82,88,85,Yes,2024-01-12 10:00:00
4,ES005,Should homework be banned?,English,9,Essay Writing,350.0,110,78,80,78,Yes,2024-01-13 11:00:00

In [10]:
print("Shape:", essay_df.shape)
print(essay_df.columns.tolist())
print(essay_df.isnull().sum())
print("Duplicates:", essay_df.duplicated().sum())

Shape: (8, 12)
['id', 'essay_topic', 'subject', 'grade_level', 'agent_type', 'word_count', 'grammar_score', 'structure_score', 'originality_score', 'overall_score', 'feedback_given', 'timestamp']
id                   0
essay_topic          1
subject              0
grade_level          0
agent_type           0
word_count           1
grammar_score        0
structure_score      0
originality_score    0
overall_score        0
feedback_given       0
timestamp            0
dtype: int64
Duplicates: 0

In [11]:
essay_df = essay_df.drop_duplicates()
essay_df = essay_df.fillna("unknown")

In [13]:
essay_df.to_csv('../data/cleaned/cleaned_essay_assistance.csv', index=False)

In [14]:
qa_df = pd.read_csv('../data/qa_interactions_raw.csv')
qa_df.head()

,id,student_query,subject,grade_level,agent_type,response_time_sec,student_rating,resolved,timestamp,session_id
0,QA001,What is Newton's second law?,Physics,10,Q&A,3.2,4.0,Yes,2024-01-10 09:15:00,S001
1,QA002,Explain photosynthesis in detail,Biology,9,Q&A,5.1,5.0,Yes,2024-01-10 10:02:00,S002
2,QA003,How do I solve quadratic equations?,Mathematics,11,Q&A,4.8,3.0,Yes,2024-01-10 11:30:00,S003
3,QA004,What caused World War I?,History,10,Q&A,NaN,NaN,No,2024-01-11 08:45:00,S004
4,QA005,Difference between mitosis and meiosis,Biology,12,Q&A,6.0,5.0,Yes,2024-01-11 09:00:00,S005

In [15]:
print(qa_df.shape)
print(qa_df.isnull().sum())
print(qa_df.duplicated().sum())

(12, 10)
id                   0
student_query        1
subject              0
grade_level          0
agent_type           0
response_time_sec    1
student_rating       1
resolved             0
timestamp            0
session_id           0
dtype: int64
0

In [16]:
qa_df = qa_df.drop_duplicates()
qa_df = qa_df.fillna("unknown")
qa_df.to_csv('../data/cleaned/cleaned_qa_interactions.csv', index=False)

In [17]:
study_df = pd.read_csv('../data/study_schedules_raw.csv')
study_df.head()

,id,student_id,subject,planned_date,study_duration_min,completed,agent_suggestion,difficulty_level,performance_after,timestamp
0,SP001,STU101,Mathematics,2024-01-15,60,Yes,Yes,Hard,78.0,2024-01-15 18:00:00
1,SP002,STU102,Physics,2024-01-15,45,Yes,Yes,Medium,82.0,2024-01-15 19:00:00
2,SP003,STU103,Chemistry,2024-01-16,-30,No,Yes,Easy,NaN,2024-01-16 09:00:00
3,SP004,STU101,Biology,2024-01-16,90,Yes,No,Medium,88.0,2024-01-16 20:00:00
4,SP005,STU104,English,2024-01-17,30,yes,Yes,easy,75.0,2024-01-17 08:00:00

In [18]:
print(study_df.shape)
print(study_df.isnull().sum())

study_df = study_df.drop_duplicates()
study_df = study_df.fillna("unknown")

study_df.to_csv('../data/cleaned/cleaned_study_schedules.csv', index=False)

(10, 10)
id                    0
student_id            1
subject               0
planned_date          0
study_duration_min    0
completed             0
agent_suggestion      0
difficulty_level      0
performance_after     2
timestamp             0
dtype: int64

In [20]:
excel_df = pd.read_excel('../data/academic_ai_raw_data.xlsx')
excel_df.head()

,ID,Student Query,Subject,Grade Level,Agent Type,Response Time Sec,Student Rating,Resolved,Timestamp,Session ID
0,QA001,What is Newton's second law?,Physics,10,Q&A,3.2,4.0,Yes,2024-01-10 09:15:00,S001
1,QA002,Explain photosynthesis in detail,Biology,9,Q&A,5.1,5.0,Yes,2024-01-10 10:02:00,S002
2,QA003,How do I solve quadratic equations?,Mathematics,11,Q&A,4.8,3.0,Yes,2024-01-10 11:30:00,S003
3,QA004,What caused World War I?,History,10,Q&A,NaN,NaN,No,2024-01-11 08:45:00,S004
4,QA005,Difference between mitosis and meiosis,Biology,12,Q&A,6.0,5.0,Yes,2024-01-11 09:00:00,S005

In [21]:
print(excel_df.shape)
print(excel_df.isnull().sum())

(12, 10)
ID                   0
Student Query        1
Subject              0
Grade Level          0
Agent Type           0
Response Time Sec    1
Student Rating       1
Resolved             0
Timestamp            0
Session ID           0
dtype: int64

In [22]:
excel_df = excel_df.drop_duplicates()
excel_df = excel_df.fillna("unknown")

excel_df.to_csv('../data/cleaned/cleaned_academic_ai_excel.csv', index=False)

In [23]:
with open('../data/academic_ai_raw_data.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

print(type(data))

<class 'dict'>

In [24]:
print(data.keys())

dict_keys(['project', 'collection_date', 'source', 'datasets', 'known_issues'])

In [25]:
for key in data:
    print(key, type(data[key]))

project <class 'str'>
collection_date <class 'str'>
source <class 'str'>
datasets <class 'dict'>
known_issues <class 'list'>

In [26]:
print(data["datasets"].keys())

dict_keys(['qa_interactions', 'essay_assistance', 'study_schedules'])

In [27]:
for key in data["datasets"]:
    print(key, type(data["datasets"][key]))

qa_interactions <class 'list'>
essay_assistance <class 'list'>
study_schedules <class 'list'>

In [28]:
import pandas as pd

qa_json_df = pd.DataFrame(data["datasets"]["qa_interactions"])
essay_json_df = pd.DataFrame(data["datasets"]["essay_assistance"])
study_json_df = pd.DataFrame(data["datasets"]["study_schedules"])

In [29]:
qa_json_df.head()

,id,student_query,subject,grade_level,agent_type,response_time_sec,student_rating,resolved,timestamp,session_id
0,QA001,What is Newton's second law?,Physics,10,Q&A,3.2,4.0,Yes,2024-01-10 09:15:00,S001
1,QA002,Explain photosynthesis in detail,Biology,9,Q&A,5.1,5.0,Yes,2024-01-10 10:02:00,S002
2,QA003,How do I solve quadratic equations?,Mathematics,11,Q&A,4.8,3.0,Yes,2024-01-10 11:30:00,S003
3,QA004,What caused World War I?,History,10,Q&A,NaN,NaN,No,2024-01-11 08:45:00,S004
4,QA005,Difference between mitosis and meiosis,Biology,12,Q&A,6.0,5.0,Yes,2024-01-11 09:00:00,S005

In [30]:
essay_json_df.head()

,id,essay_topic,subject,grade_level,agent_type,word_count,grammar_score,structure_score,originality_score,overall_score,feedback_given,timestamp
0,ES001,Impact of social media on youth,English,11,Essay Writing,520.0,88,90,85,87,Yes,2024-01-10 13:00:00
1,ES002,Climate change and its effects,Environmental Science,12,Essay Writing,610.0,92,88,90,90,Yes,2024-01-11 14:00:00
2,ES003,Role of technology in education,English,10,Essay Writing,NaN,75,70,80,75,No,2024-01-11 15:00:00
3,ES004,Importance of biodiversity,Biology,11,Essay Writing,480.0,85,82,88,85,Yes,2024-01-12 10:00:00
4,ES005,Should homework be banned?,English,9,Essay Writing,350.0,110,78,80,78,Yes,2024-01-13 11:00:00

In [31]:
study_json_df.head()

,id,student_id,subject,planned_date,study_duration_min,completed,agent_suggestion,difficulty_level,performance_after,timestamp
0,SP001,STU101,Mathematics,2024-01-15,60,Yes,Yes,Hard,78.0,2024-01-15 18:00:00
1,SP002,STU102,Physics,2024-01-15,45,Yes,Yes,Medium,82.0,2024-01-15 19:00:00
2,SP003,STU103,Chemistry,2024-01-16,-30,No,Yes,Easy,NaN,2024-01-16 09:00:00
3,SP004,STU101,Biology,2024-01-16,90,Yes,No,Medium,88.0,2024-01-16 20:00:00
4,SP005,STU104,English,2024-01-17,30,yes,Yes,easy,75.0,2024-01-17 08:00:00

In [32]:
print("QA shape:", qa_json_df.shape)
print("Essay shape:", essay_json_df.shape)
print("Study shape:", study_json_df.shape)

QA shape: (12, 10)
Essay shape: (8, 12)
Study shape: (10, 10)

In [33]:
print(qa_json_df.isnull().sum())
print(essay_json_df.isnull().sum())
print(study_json_df.isnull().sum())

id                   0
student_query        0
subject              0
grade_level          0
agent_type           0
response_time_sec    1
student_rating       1
resolved             0
timestamp            0
session_id           0
dtype: int64
id                   0
essay_topic          0
subject              0
grade_level          0
agent_type           0
word_count           1
grammar_score        0
structure_score      0
originality_score    0
overall_score        0
feedback_given       0
timestamp            0
dtype: int64
id                    0
student_id            1
subject               0
planned_date          0
study_duration_min    0
completed             0
agent_suggestion      0
difficulty_level      0
performance_after     2
timestamp             0
dtype: int64

In [34]:
qa_json_df = qa_json_df.drop_duplicates().fillna("unknown")
essay_json_df = essay_json_df.drop_duplicates().fillna("unknown")
study_json_df = study_json_df.drop_duplicates().fillna("unknown")

In [35]:
qa_json_df.to_csv('../data/cleaned/cleaned_json_qa.csv', index=False)
essay_json_df.to_csv('../data/cleaned/cleaned_json_essay.csv', index=False)
study_json_df.to_csv('../data/cleaned/cleaned_json_study.csv', index=False)

print("Saved all cleaned JSON datasets!")

Saved all cleaned JSON datasets!

In [1]:
df_anxiety = pd.read_csv('../data/raw/ai_dependency_career_anxiety_students.csv')
print(df_anxiety.head())

NameError: name 'pd' is not defined

In [2]:
import pandas as pd
import numpy as np

In [3]:
df_anxiety = pd.read_csv('../data/raw/ai_dependency_career_anxiety_students.csv')
print(df_anxiety.head())

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/ai_dependency_career_anxiety_students.csv'

In [4]:
import os
print(os.getcwd())

c:\multi-agent-ai-system-for-academic-assistance\src

In [5]:
import os
print(os.listdir('../data'))

['cleaned', 'raw', 'README.md']

In [6]:
import os
print(os.listdir('../data/raw'))

['academic_ai_raw_data.json', 'academic_ai_raw_data.xlsx', 'coursea_data.csv', 'essay_assistance_raw.csv', 'python_faq_dataset.csv', 'qa_interactions_raw.csv', 'studentAssessment.csv', 'study_schedules_raw.csv', 'thinkpython2.pdf']

In [7]:
import pandas as pd

df_anxiety = pd.read_csv('../data/raw/ai_dependency_career_anxiety_students.csv')
print(df_anxiety.head())

  student_id  age  gender  degree_type                stream  year_of_study  \
0  STU_00001   25    Male  B.Tech/B.E.  Engineering (Non-CS)              3
1  STU_00002   20  Female  B.Tech/B.E.  Engineering (Non-CS)              4
2  STU_00003   25  Female          MBA                 CS/IT              1
3  STU_00004   23    Male  B.Tech/B.E.                 CS/IT              1
4  STU_00005   22  Female          MBA                 CS/IT              1

  college_tier urban_or_rural  daily_ai_tool_usage_hrs primary_ai_tools_used  \
0       Tier 3          Rural                      0.3            Perplexity
1       Tier 3          Urban                      1.9               ChatGPT
2       Tier 3          Urban                      3.6                Gemini
3       Tier 1          Urban                      4.1        GitHub Copilot
4       Tier 1          Urban                      3.4               ChatGPT

   ... daily_study_hours  self_learning_hours_per_week  \
0  ...               3.5                           8.7
1  ...               2.4                           8.2
2  ...               2.3                          16.4
3  ...               7.7                          15.0
4  ...               2.4                           1.1

   skill_development_courses_taken  social_media_hrs_per_day  sleep_hours  \
0                                2                       1.5          8.5
1                                3                       4.2          8.3
2                                1                       2.3          7.0
3                                3                       2.6          7.2
4                                2                       1.9          8.0

   stress_level  burnout_score  motivation_score  seeks_career_counseling  \
0             1              3                 6                      0.0
1             4              5                 3                      0.0
2             5              9                 3                      1.0
3             6              6                 6                      0.0
4             3              5                 4                      0.0

   overall_career_readiness_score
0                            9.09
1                            6.03
2                            6.68
3                            7.71
4                            4.64

[5 rows x 30 columns]

In [8]:
print("Shape:", df_anxiety.shape)
print(df_anxiety.isnull().sum())
print("Duplicates:", df_anxiety.duplicated().sum())

Shape: (15000, 30)
student_id                            0
age                                   0
gender                                0
degree_type                           0
stream                                0
year_of_study                         0
college_tier                          0
urban_or_rural                        0
daily_ai_tool_usage_hrs               0
primary_ai_tools_used              3215
uses_ai_for_assignments               0
ai_replaces_own_thinking_score        0
ai_dependency_score                   0
placement_anxiety_score               0
fear_of_job_loss_to_ai                0
career_clarity_score                  0
internship_experience                 0
weekly_job_application_count          0
resume_confidence_score               0
interview_anxiety_score               0
daily_study_hours                     0
self_learning_hours_per_week        233
skill_development_courses_taken       0
social_media_hrs_per_day            210
sleep_hours                         203
stress_level                          0
burnout_score                         0
motivation_score                      0
seeks_career_counseling             220
overall_career_readiness_score        0
dtype: int64
Duplicates: 0

In [9]:
df_anxiety = df_anxiety.drop_duplicates()
df_anxiety = df_anxiety.fillna("unknown")

In [10]:
df_anxiety.to_csv('../data/cleaned/cleaned_ai_anxiety.csv', index=False)
print("Saved!")

Saved!

In [1]:
import pandas as pd
import os

# Raw and cleaned file pairs
datasets = {
    'academic_ai_excel': ('academic_ai_raw_data.xlsx', 'cleaned_academic_ai_excel.csv'),
    'ai_anxiety': ('ai_dependency_career_anxiety_students.csv', 'cleaned_ai_anxiety.csv'),
    'coursea_data': ('coursea_data.csv', 'cleaned_coursea_data.csv'),
    'essay_assistance': ('essay_assistance_raw.csv', 'cleaned_essay_assistance.csv'),
    'python_faq': ('python_faq_dataset.csv', 'cleaned_python_faq.csv'),
    'qa_interactions': ('qa_interactions_raw.csv', 'cleaned_qa_interactions.csv'),
    'student_por': ('student-por.csv', 'cleaned_student_por.csv'),
    'studentAssessment': ('studentAssessment.csv', 'cleaned_studentAssessment.csv'),
    'students_performance': ('StudentsPerformance.csv', 'cleaned_students_performance.csv'),
    'study_schedules': ('study_schedules_raw.csv', 'cleaned_study_schedules.csv'),
}

raw_folder = '../data/raw/'
cleaned_folder = '../data/cleaned/'

print(f"{'Dataset':<25} {'Raw Rows':<12} {'Cleaned Rows':<14} {'Rows Removed':<12}")
print("-" * 65)

for name, (raw_file, clean_file) in datasets.items():
    try:
        raw_path = raw_folder + raw_file
        clean_path = cleaned_folder + clean_file
        
        if raw_file.endswith('.xlsx'):
            raw_df = pd.read_excel(raw_path)
        else:
            raw_df = pd.read_csv(raw_path)
            
        clean_df = pd.read_csv(clean_path)
        
        raw_rows = len(raw_df)
        clean_rows = len(clean_df)
        removed = raw_rows - clean_rows
        
        print(f"{name:<25} {raw_rows:<12} {clean_rows:<14} {removed:<12}")
    except Exception as e:
        print(f"{name:<25} Error: {e}")

Dataset                   Raw Rows     Cleaned Rows   Rows Removed
-----------------------------------------------------------------
academic_ai_excel         12           12             0
ai_anxiety                15000        15000          0
coursea_data              891          891            0
essay_assistance          8            8              0
python_faq                21677        21677          0
qa_interactions           12           12             0
student_por               649          649            0
studentAssessment         173912       173912         0
students_performance      1000         1000           0
study_schedules           10           10             0